# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pi2nucleo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pi2nucleo.proto',
  package='pi2nucleo_package',
  syntax='proto2',
  serialized_pb=_b('\n\x0fpi2nucleo.proto\x12\x11pi2nucleo_package\"D\n\x11Pi2Nucleo_Message\x12\r\n\x05steer\x18\x01 \x01(\x02\x12\r\n\x05speed\x18\x02 \x01(\x02\x12\x11\n\tdebug_lvl\x18\x03 \x01(\x05')
)




_PI2NUCLEO_MESSAGE = _descriptor.Descriptor(
  name='Pi2Nucleo_Message',
  full_name='pi2nucleo_package.Pi2Nucleo_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steer', full_name='pi2nucleo_package.Pi2Nucleo_Message.steer', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='pi2nucleo_package.Pi2Nucleo_Message.speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debug_lvl', full_name='pi2nucleo_package.Pi2Nucleo_Message.debug_lvl', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Pi2Nucleo_Message'] = _PI2NUCLEO_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pi2Nucleo_Message = _reflection.GeneratedProtocolMessageType('Pi2Nucleo_Message', (_message.Message,), dict(
  DESCRIPTOR = _PI2NUCLEO_MESSAGE,
  __module__ = 'pi2nucleo_pb2'
  # @@protoc_insertion_point(class_scope:pi2nucleo_package.Pi2Nucleo_Message)
  ))
_sym_db.RegisterMessage(Pi2Nucleo_Message)


# @@protoc_insertion_point(module_scope)
